routes/admin.php
<?php 

Route::get('/', 'Admin\HomeController@index');
Route::get('/home', 'Admin\HomeController@index')->name('home');

//Profile
Route::get('/profile', 'Admin\ProfileController@show')->name('profile');
Route::post('/profile', 'Admin\ProfileController@store')->name('profile');

//Settings
Route::get('/settings', 'Admin\SettingsController@index')->name('settings.index');
Route::post('/settings', 'Admin\SettingsController@store')->name('settings.store');

//Packages
Route::resource('packages', 'Admin\PackageController');
Route::resource('package-features', 'Admin\PackageFeatureController');

// Live Videos
Route::resource('live-videos', 'Admin\LiveVideoController');
Route::get('/fetchLiveVideo', 'Admin\LiveVideoController@fetchLiveVideo');
Route::get('/deleteLiveVideo', 'Admin\LiveVideoController@deleteLiveVideo');

// Recorded Videos
Route::resource('recorded-videos', 'Admin\RecordedVideoController');
Route::get('/fetchVideo', 'Admin\RecordedVideoController@fetchVideo');
Route::get('/deleteVideo', 'Admin\RecordedVideoController@deleteVideo');

// Users
Route::resource('users', 'Admin\UserController');

// Category
Route::resource('category', 'Admin\CategoryController');

//Reports
Route::get('/reports', 'Admin\ReportController@index')->name('reports.index');
Route::post('/reports', 'Admin\ReportController@store')->name('reports.store');

//Admin Activities
Route::resource('admin-activity', 'Admin\AdminActivityController');
Route::get('/adminMassDelete', 'Admin\AdminActivityController@massDelete')->name('admin-activity.massDelete');

//User Activities
Route::resource('user-activity', 'Admin\UserActivityController');
Route::get('/userMassDelete', 'Admin\UserActivityController@massDelete')->name('user-activity.massDelete');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/********  Front End Routes *******/

//Home Routes
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('homepage');
Route::get('/referral/{code}', 'User\ReferralController@refferal')->name('user.referral');
//Membership 
Route::get('/membership', 'HomeController@membership')->name('membership.index');
Route::get('/getRec', 'Zoom\MeetingController@getRec')->name('admin.recordings');

//Autentication
Auth::routes(['register' => false,]);
// Registration Routes
Route::get('/buy/{slug}', 'RegisterController@index')->name('register.index');
Route::post('/signup', 'RegisterController@store')->name('register.store');
// route for to show payment form using get method
Route::get('/confirm-payment/{slug}/{id}', 'RegisterController@pay')->name('register.pay');
// route for make payment request using post method
Route::post('dopayment', 'RegisterController@dopayment')->name('dopayment');


/*************  Admin Routes ********/

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout')->name('admin.logout');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('admin.password.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');

});

/*************  Admin Routes Ends ********/

/*************  User Routes ********/

Route::group(['prefix' => 'user'], function () {

    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('user.login');
    Route::post('/login', 'Auth\LoginController@login');

    Route::middleware(['auth'])->group(function () {

        Route::get('/', 'User\HomeController@index')->name('home');
        Route::get('/home', 'User\HomeController@index');
        Route::get('/subscription', 'User\SubscriptionController@index')->name('user.subscription');
        Route::get('/recorded-course', 'User\RecordedCourseController@index')->name('user.recorded-course');
        Route::get('/recorded-course/show', 'User\RecordedCourseController@show')->name('user.recorded-course.show');
        Route::get('/profile', 'User\ProfileController@index')->name('user.profile');
        Route::get('/profile/edit', 'User\ProfileController@edit')->name('user.profile.edit');
        Route::post('/profile/update', 'User\ProfileController@update')->name('user.profile.update');
        Route::get('/referral-link', 'User\ReferLinkController@index')->name('user.referral-link');
        Route::get('/referralMail', 'User\ReferLinkController@referralMail')->name('user.referral-mail');
        Route::get('/settings', 'User\SettingsController@index')->name('user.settings');
        Route::post('/profile/passwordReset', 'User\SettingsController@update')->name('user.password.reset');
        Route::post('/savePayment', 'User\RenewalController@savePayment')->name('user.savePayment');
        Route::get('/getData', 'User\RenewalController@getData')->name('user.package.data');
      
    });



});

resources/views/admin/home.blade.php
@extends('admin.layout.app')

@section('content')
<!-- Page Content -->
<div class="content">                    
                    <div class="row gutters-tiny invisible" data-toggle="appear">
                        <!-- Row #4 -->
                        <div class="col-md-4">
                            <div class="block block-transparent bg-primary">
                                <div class="block-content block-content-full">
                                    <div class="py-20 text-center">
                                        <div class="mb-20">
                                            <i class="fa fa-bar-chart fa-4x text-primary-light"></i>
                                        </div>
                                        <div class="font-size-h4 font-w600 text-white">Reports</div>
                                        <div class="text-white-op">Contains Payment Reports</div>
                                        <div class="pt-20">
                                            <a class="btn btn-rounded btn-alt-primary" href="{{ route('admin.reports.index') }}">
                                                <i class="fa fa-eye mr-5"></i> View Reports
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="block block-transparent bg-info">
                                <div class="block-content block-content-full">
                                    <div class="py-20 text-center">
                                        <div class="mb-20">
                                            <i class="fa fa-users fa-4x text-info-light"></i>
                                        </div>
                                        <div class="font-size-h4 font-w600 text-white">Users</div>
                                        <div class="text-white-op">Contains Users Lists</div>
                                        <div class="pt-20">
                                            <a class="btn btn-rounded btn-alt-info" href="{{ route('admin.users.index') }}">
                                                <i class="fa fa-eye mr-5"></i> View Users
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="block block-transparent bg-success">
                                <div class="block-content block-content-full">
                                    <div class="py-20 text-center">
                                        <div class="mb-20">
                                            <i class="fa fa-gift fa-4x text-success-light"></i>
                                        </div>
                                        <div class="font-size-h4 font-w600 text-white">Subscription Packages</div>
                                        <div class=" text-white-op">Contains Packages Lists</div>
                                        <div class="pt-20">
                                            <a class="btn btn-rounded btn-alt-success" href="{{ route('admin.packages.index') }}">
                                                <i class="fa fa-eye mr-5"></i> View Packages
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="block block-transparent bg-success">
                                <div class="block-content block-content-full">
                                    <div class="py-20 text-center">
                                        <div class="mb-20">
                                            <i class="fa fa-key fa-4x text-success-light"></i>
                                        </div>
                                        <div class="font-size-h4 font-w600 text-white">Package Features</div>
                                        <div class=" text-white-op">Contains Features Lists</div>
                                        <div class="pt-20">
                                            <a class="btn btn-rounded btn-alt-success" href="{{ route('admin.package-features.index') }}">
                                                <i class="fa fa-eye mr-5"></i> View Features
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="block block-transparent bg-primary">
                                <div class="block-content block-content-full">
                                    <div class="py-20 text-center">
                                        <div class="mb-20">
                                            <i class="fa fa-television fa-4x text-primary-light"></i>
                                        </div>
                                        <div class="font-size-h4 font-w600 text-white">Live Courses</div>
                                        <div class="text-white-op">Contains Live Courses</div>
                                        <div class="pt-20">
                                            <a class="btn btn-rounded btn-alt-primary" href="{{ route('admin.live-videos.index') }}">
                                                <i class="fa fa-eye mr-5"></i> View LiveCourses
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="block block-transparent bg-info">
                                <div class="block-content block-content-full">
                                    <div class="py-20 text-center">
                                        <div class="mb-20">
                                            <i class="fa fa-video-camera fa-4x text-info-light"></i>
                                        </div>
                                        <div class="font-size-h4 font-w600 text-white">Recorded Courses</div>
                                        <div class="text-white-op">Contains Recorded Courses</div>
                                        <div class="pt-20">
                                            <a class="btn btn-rounded btn-alt-info" href="{{ route('admin.recorded-videos.index') }}">
                                                <i class="fa fa-eye mr-5"></i> View RecordedCourses
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        <!-- END Row #4 -->
                    </div>
</div>               
<!-- END Page Content -->

@endsection
@section('js_after')
@endsection