routes/admin.php
<?php 

Route::get('/', 'Admin\HomeController@index');
Route::get('/home', 'Admin\HomeController@index')->name('home');

//Profile
Route::get('/profile', 'Admin\ProfileController@show')->name('profile');
Route::post('/profile', 'Admin\ProfileController@store')->name('profile');

//Settings
Route::get('/settings', 'Admin\SettingsController@index')->name('settings.index');
Route::post('/settings', 'Admin\SettingsController@store')->name('settings.store');

//Packages
Route::resource('packages', 'Admin\PackageController');
Route::resource('package-features', 'Admin\PackageFeatureController');

// Live Videos
Route::resource('live-videos', 'Admin\LiveVideoController');
Route::get('/fetchLiveVideo', 'Admin\LiveVideoController@fetchLiveVideo');
Route::get('/deleteLiveVideo', 'Admin\LiveVideoController@deleteLiveVideo');

// Recorded Videos
Route::resource('recorded-videos', 'Admin\RecordedVideoController');
Route::get('/fetchVideo', 'Admin\RecordedVideoController@fetchVideo');
Route::get('/deleteVideo', 'Admin\RecordedVideoController@deleteVideo');

// Users
Route::resource('users', 'Admin\UserController');

// Category
Route::resource('category', 'Admin\CategoryController');

//Reports
Route::get('/reports', 'Admin\ReportController@index')->name('reports.index');
Route::post('/reports', 'Admin\ReportController@store')->name('reports.store');

//Admin Activities
Route::resource('admin-activity', 'Admin\AdminActivityController');
Route::get('/adminMassDelete', 'Admin\AdminActivityController@massDelete')->name('admin-activity.massDelete');

//User Activities
Route::resource('user-activity', 'Admin\UserActivityController');
Route::get('/userMassDelete', 'Admin\UserActivityController@massDelete')->name('user-activity.massDelete');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/********  Front End Routes *******/

//Home Routes
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('homepage');
Route::get('/referral/{code}', 'User\ReferralController@refferal')->name('user.referral');
//Membership 
Route::get('/membership', 'HomeController@membership')->name('membership.index');
Route::get('/getRec', 'Zoom\MeetingController@getRec')->name('admin.recordings');

//Autentication
Auth::routes(['register' => false,]);
// Registration Routes
Route::get('/buy/{slug}', 'RegisterController@index')->name('register.index');
Route::post('/signup', 'RegisterController@store')->name('register.store');
// route for to show payment form using get method
Route::get('/confirm-payment/{slug}/{id}', 'RegisterController@pay')->name('register.pay');
// route for make payment request using post method
Route::post('dopayment', 'RegisterController@dopayment')->name('dopayment');


/*************  Admin Routes ********/

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout')->name('admin.logout');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('admin.password.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');

});

/*************  Admin Routes Ends ********/

/*************  User Routes ********/

Route::group(['prefix' => 'user'], function () {

    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('user.login');
    Route::post('/login', 'Auth\LoginController@login');

    Route::middleware(['auth'])->group(function () {

        Route::get('/', 'User\HomeController@index')->name('home');
        Route::get('/home', 'User\HomeController@index');
        Route::get('/subscription', 'User\SubscriptionController@index')->name('user.subscription');
        Route::get('/recorded-course', 'User\RecordedCourseController@index')->name('user.recorded-course');
        Route::get('/recorded-course/show', 'User\RecordedCourseController@show')->name('user.recorded-course.show');
        Route::get('/profile', 'User\ProfileController@index')->name('user.profile');
        Route::get('/profile/edit', 'User\ProfileController@edit')->name('user.profile.edit');
        Route::post('/profile/update', 'User\ProfileController@update')->name('user.profile.update');
        Route::get('/referral-link', 'User\ReferLinkController@index')->name('user.referral-link');
        Route::get('/referralMail', 'User\ReferLinkController@referralMail')->name('user.referral-mail');
        Route::get('/settings', 'User\SettingsController@index')->name('user.settings');
        Route::post('/profile/passwordReset', 'User\SettingsController@update')->name('user.password.reset');
        Route::post('/savePayment', 'User\RenewalController@savePayment')->name('user.savePayment');
        Route::get('/getData', 'User\RenewalController@getData')->name('user.package.data');
      
    });



});

app/Http/Controllers/Admin/AdminActivityController.php
<?php

namespace App\Http\Controllers\Admin;
use App\ActivityLog;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminActivityController extends Controller
{
    public function index()
    {
        return view('admin.admin-activity.index',['datas' => ActivityLog::latest("updated_at")->paginate(10)]);
    }
    public function destroy($id)
    {
        $res = ActivityLog::where('id',$id)->delete();
        if ($res) {
            return redirect()->back()->with('success', 'Successfully deleted the activity.');
        } else {
            return redirect()->back()->with('error', 'Failed to delete the activity. Please try again.');
        }
    }
    public function massDelete()
    {
        $res = ActivityLog::whereNotNull('id')->delete();
        if($res){
            return response()->json(['success'=>'Category Updated Successfully']);
        }
    }
}

resources/views/admin/admin-activity/index.blade.php
@extends('admin.layout.app')

@section('content')
<!-- Page Content -->
<div class="content">
    <nav class="breadcrumb bg-white push">
        <a class="breadcrumb-item" href="{{ route('admin.home') }}">Dashboard</a>
        <span class="breadcrumb-item active">Admin Activities</span>
    </nav>

    <!-- Dynamic Table Full -->
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">View Admin Activities</h3>
            <div align="right">
                <button class="btn btn-info" onclick="massDelete()">Delete All</button>
            </div>
        </div>
        <div class="block-content block-content-full">

        @if (session('error'))
            <div class="alert alert-danger alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <p class="mb-0">{{ session('error') }}</p>
            </div>
        @endif
        @if (session('success'))
            <div class="alert alert-success alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <p class="mb-0">{{ session('success') }}</p>
            </div>
        @endif
       
        <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
            <thead>
                <tr>
                    <th style="text-transform: none !important;">Sl.No</th>
                    <th style="text-transform: none !important;">Name</th>
                    <th style="text-transform: none !important;">Description</th>
                    <th style="text-transform: none !important;">Delete</th>
                    <th style="text-transform: none !important;">Last Modified</th>
                </tr>
            </thead>
            
            <tbody>
                @if($datas->count())
                    @foreach ($datas as $data)
                    <tr>
                        <td class="text-center"> {{ $loop->iteration }} </td>
                        <td class="font-w600"> {{ @$data->log_name }}</td>
                        <td class="d-none d-sm-table-cell">{{ @$data->description }}</td>
                        <td align="center">
                            <div class="btn">
                                <button type="button" class="btn btn-sm btn-secondary" data-toggle="tooltip"
                                            title="Delete"
                                            onclick="event.preventDefault(); if(confirm('Are you sure to delete this activity?')){ document.getElementById('delete-admin-activity-{{ $data->id }}').submit();}">
                                            <i class="fa fa-times"></i>
                                </button>
                                <form id="delete-admin-activity-{{ $data->id }}"
                                            action="{{ route('admin.admin-activity.destroy', $data->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                </form>
                            </div>
                        </td>
                        <td>{{ $data->updated_at->diffForHumans() }}</td>
                    </tr>
                    @endforeach
                @else
                <tr class="no-data">
                    <td colspan="7" class="text-center">No data found</td>
                </tr>
                @endif
            </tbody>
        </table>
        </div>
    </div>
    <!-- END Dynamic Table Full -->
</div>               
<!-- END Page Content -->

@endsection
@section('js_after')
<script>
    function massDelete() {
        var r = confirm("Are you sure to delete all the activities!");
        if(r==true)
        {
            $.ajax({
                url: "{{ route('admin.admin-activity.massDelete') }}",
                type:"get",
                success:function(response){
                    console.log(response);
                    if(response) {
                        alert("Activities deleted successfully")
                        location.reload();
                    }
                },
            });
        }
    }
</script>
@endsection