routes/admin.php
<?php 

Route::get('/', 'Admin\HomeController@index');
Route::get('/home', 'Admin\HomeController@index')->name('home');

//Profile
Route::get('/profile', 'Admin\ProfileController@show')->name('profile');
Route::post('/profile', 'Admin\ProfileController@store')->name('profile');

//Settings
Route::get('/settings', 'Admin\SettingsController@index')->name('settings.index');
Route::post('/settings', 'Admin\SettingsController@store')->name('settings.store');

//Packages
Route::resource('packages', 'Admin\PackageController');
Route::resource('package-features', 'Admin\PackageFeatureController');

// Live Videos
Route::resource('live-videos', 'Admin\LiveVideoController');
Route::get('/fetchLiveVideo', 'Admin\LiveVideoController@fetchLiveVideo');
Route::get('/deleteLiveVideo', 'Admin\LiveVideoController@deleteLiveVideo');

// Recorded Videos
Route::resource('recorded-videos', 'Admin\RecordedVideoController');
Route::get('/fetchVideo', 'Admin\RecordedVideoController@fetchVideo');
Route::get('/deleteVideo', 'Admin\RecordedVideoController@deleteVideo');

// Users
Route::resource('users', 'Admin\UserController');

// Category
Route::resource('category', 'Admin\CategoryController');

//Reports
Route::get('/reports', 'Admin\ReportController@index')->name('reports.index');
Route::post('/reports', 'Admin\ReportController@store')->name('reports.store');

//Admin Activities
Route::resource('admin-activity', 'Admin\AdminActivityController');
Route::get('/adminMassDelete', 'Admin\AdminActivityController@massDelete')->name('admin-activity.massDelete');

//User Activities
Route::resource('user-activity', 'Admin\UserActivityController');
Route::get('/userMassDelete', 'Admin\UserActivityController@massDelete')->name('user-activity.massDelete');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/********  Front End Routes *******/

//Home Routes
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('homepage');
Route::get('/referral/{code}', 'User\ReferralController@refferal')->name('user.referral');
//Membership 
Route::get('/membership', 'HomeController@membership')->name('membership.index');
Route::get('/getRec', 'Zoom\MeetingController@getRec')->name('admin.recordings');

//Autentication
Auth::routes(['register' => false,]);
// Registration Routes
Route::get('/buy/{slug}', 'RegisterController@index')->name('register.index');
Route::post('/signup', 'RegisterController@store')->name('register.store');
// route for to show payment form using get method
Route::get('/confirm-payment/{slug}/{id}', 'RegisterController@pay')->name('register.pay');
// route for make payment request using post method
Route::post('dopayment', 'RegisterController@dopayment')->name('dopayment');


/*************  Admin Routes ********/

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout')->name('admin.logout');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('admin.password.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');

});

/*************  Admin Routes Ends ********/

/*************  User Routes ********/

Route::group(['prefix' => 'user'], function () {

    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('user.login');
    Route::post('/login', 'Auth\LoginController@login');

    Route::middleware(['auth'])->group(function () {

        Route::get('/', 'User\HomeController@index')->name('home');
        Route::get('/home', 'User\HomeController@index');
        Route::get('/subscription', 'User\SubscriptionController@index')->name('user.subscription');
        Route::get('/recorded-course', 'User\RecordedCourseController@index')->name('user.recorded-course');
        Route::get('/recorded-course/show', 'User\RecordedCourseController@show')->name('user.recorded-course.show');
        Route::get('/profile', 'User\ProfileController@index')->name('user.profile');
        Route::get('/profile/edit', 'User\ProfileController@edit')->name('user.profile.edit');
        Route::post('/profile/update', 'User\ProfileController@update')->name('user.profile.update');
        Route::get('/referral-link', 'User\ReferLinkController@index')->name('user.referral-link');
        Route::get('/referralMail', 'User\ReferLinkController@referralMail')->name('user.referral-mail');
        Route::get('/settings', 'User\SettingsController@index')->name('user.settings');
        Route::post('/profile/passwordReset', 'User\SettingsController@update')->name('user.password.reset');
        Route::post('/savePayment', 'User\RenewalController@savePayment')->name('user.savePayment');
        Route::get('/getData', 'User\RenewalController@getData')->name('user.package.data');
      
    });



});

app/LiveVideo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LiveVideo extends Model
{
     protected $table="live_videos";
     use Uuids;
     /**
      * Indicates if the IDs are auto-incrementing.
      *
      * @var bool
      */
     public $incrementing = false;

      /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id','video_link','title', 'meeting_id', 'passcode','description','schedule','status'
  ];

  
  public function packages()
  {
        return $this->belongsToMany('App\Package');
  }

  public function category()
  {
    return $this->hasOne('App\Category','id','category_id');
  }


  public function live_video_package()
  {
      return $this->hasMany('App\LiveVideoPackage');
  }

   
}

app/Http/Controllers/Admin/LiveVideoController.php
<?php

namespace App\Http\Controllers\Admin;

use Mail;
use App\Http\Controllers\Controller;
use App\LiveVideoPackage;
use App\Package;
use App\LiveVideo;
use App\Category;
use App\Http\Traits\ZoomJWT;
use Carbon\Carbon;
use Validator;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Mail\UserAccountActivation;


class LiveVideoController extends Controller
{
    use ZoomJWT;

    public function index()
    {
        $videos=LiveVideo::orderby("schedule", 'desc')->where('schedule','>=',Carbon::now()->subMinutes(30))->paginate(10, ['*'], 'videos');
        $inactives=LiveVideo::orderby("schedule", 'desc')->where('schedule','<',Carbon::now())->paginate(10, ['*'], 'inactives');
        $packages=Package::where('status',1)->get();
        return view('admin.live-videos.index',['videos'=>$videos,'packages'=>$packages,'inactives'=>$inactives]);
    }

    public function create()
    {
        $packages=Package::where('status',1)->get();
        $category=Category::all();
        return view('admin.live-videos.create', ['packages'=>$packages,'categories'=>$category]);
    }
    public function store(Request $request)
    {
       
        $user = auth()->guard('admin')->user();
        $validated = $request->validate([
            'video' => 'required|url',
            'start' => 'required|url',
            'title' => 'required',
            'meeting_id' => 'required',
            'passcode' => 'required',
            // 'status' => 'required',
            'category' => 'required',
            'description' => 'required',
            'package.*' => 'required',
            'date' => 'required|date',
            ],
           
        );
        //dd($validated);exit;
        $video=new LiveVideo();
        $video->video_link=$validated['video'];
        $video->start_link=$validated['start'];
        $video->title=$validated['title'];
        $video->meeting_id=$validated['meeting_id'];
        $video->passcode=$validated['passcode'];
        $video->description=$validated['description'];
        $video->schedule=$validated['date'];
        // $video->status=$validated['status'];
        $video->status=1;
        $video->video_link=$validated['video'];
        $video->category_id=$validated['category'];
        $res=$video->save();
        if($res){
            foreach($validated['package'] as $package){
                $pack_video= new LiveVideoPackage();
                $pack_video->live_video_id=$video->id;
                $pack_video->package_id=$package;
                $res=$pack_video->save();
            }
        }
        if ($res) {
            
            //activity('admin')->performedOn($user)->causedBy($user)->withProperties(['data' => $request])->log('Updated Profile.');
            return redirect()->route('admin.live-videos.index')->with('success', 'Meeting Scheduled successfully.');
        } else {
            return redirect()->back()->with('error', 'Failed to schedule meeting. Please try again.');
        }
    }

    public function edit(Request $request, $uuid)
    {
        $video = LiveVideo::where('id', $uuid)->firstorFail();
        $packages=Package::where('status',1)->get();
        $category=Category::all();
        return view('admin.live-videos.edit', ['data' => $video,'packages'=>$packages,'categories'=>$category]);
    }

    public function update(Request $request, LiveVideo $liveVideo)
    {   
        $user = auth()->guard('admin')->user();
        $validated = $request->validate([
            'video' => 'required|url',
            'title' => 'required',
            'meeting_id' => 'required',
            'passcode' => 'required',
            // 'status' => 'required',
            'category' => 'required',
            'description' => 'required',
            'package.*' => 'required',
            'date' => 'required|date',
        ]);
        $liveVideo->video_link=$validated['video'];
        $liveVideo->title=$validated['title'];
        $liveVideo->meeting_id=$validated['meeting_id'];
        $liveVideo->passcode=$validated['passcode'];
        $liveVideo->description=$validated['description'];
        $liveVideo->schedule=$validated['date'];
        // $liveVideo->status=$validated['status'];
        $liveVideo->status=1;
        $liveVideo->category_id=$validated['category'];
        $liveVideo->video_link=$validated['video'];
        $res=$liveVideo->save();

        if($res){
            LiveVideoPackage::where('live_video_id',$liveVideo->id)->delete();
            foreach($validated['package'] as $package){
                $pack_video= new LiveVideoPackage();
                $pack_video->live_video_id=$liveVideo->id;
                $pack_video->package_id=$package;
                $res=$pack_video->save();
            }
        }
        if ($res) {
            //activity('admin')->performedOn($user)->causedBy($user)->withProperties(['data' => $request])->log('Updated Profile.');
            return redirect()->route('admin.live-videos.index')->with('success', 'Successfully updated meeting.');
        } else {
            return redirect()->back()->with('error', 'Failed to update meeting. Please try again.');
        }
    }

    public function destroy(LiveVideo $liveVideo, Request $request)
    {
        $id=$liveVideo->meeting_id;
        $path = 'meetings/' . $id;
        $this->zoomDelete($path);
        $res = $liveVideo->delete();
        if ($res) {
            return redirect()->back()->with('success', 'Successfully deleted the meeting.');
        } else {
            return redirect()->back()->with('error', 'Failed to delete the meeting. Please try again.');
        }
    }

}

resources/views/admin/live-videos/index.blade.php
@extends('admin.layout.app')

@section('content')
<!-- Page Content -->
<div class="content">
    <nav class="breadcrumb bg-white push">
        <a class="breadcrumb-item" href="{{ route('admin.home') }}">Dashboard</a>
        <span class="breadcrumb-item active">Live Videos</span>
    </nav>

    <!-- Dynamic Table Full -->
    <div class="block">
        <div class="block-header block-header-default">
            <h3 class="block-title">View Live Videos</h3>
        </div>
        <div class="block-content block-content-full">

        @if (session('error'))
            <div class="alert alert-danger alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <p class="mb-0">{{ session('error') }}</p>
            </div>
        @endif
        @if (session('success'))
            <div class="alert alert-success alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <p class="mb-0">{{ session('success') }}</p>
            </div>
        @endif
        <h4 align="center">Upcoming Meetings</h4>
        <table id="live-videos" class="table table-bordered table-striped table-vcenter">
            <thead>
                <tr>
                    <th style="text-transform: none !important;">Sl.No</th>
                    <th style="text-transform: none !important;">Meeting Title</th>
                    <th style="text-transform: none !important;">Meeting Id</th>
                    <th style="text-transform: none !important;">Packages</th>
                    <th style="text-transform: none !important;">Scheduled Date / Time</th>
                    <th style="text-transform: none !important;">Category</th>
                    <th style="text-transform: none !important;">Actions</th>

                </tr>
            </thead>
            <tbody>
                @if($videos->count())
                @foreach ($videos as $data)
                <tr>
                    <td class="text-center"> {{ $loop->iteration }} </td>
                    <td class="font-w600"> {{ @$data->title }}</td>
                    <td class="font-w600"> {{ @$data->meeting_id }}</td>
                    <td class="d-none d-sm-table-cell">
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            @foreach ($data->packages as $package)
                                <span class="badge badge-success">{{ $package->name }}</span>
                            @endforeach
                        </div>
                    </td>
                    <td>
                        {{ Carbon::parse(@$data->schedule)->format('d M Y h:i:s A') }}
                    </td>
                    <td>
                        {{ @$data->category->category}}
                    </td>
                    <td>
                        <div class="btn-group">
                            @if($data->schedule >= Carbon::now()->subMinutes(30))
                                <a target="_blank" href="{{$data->start_link}}"
                                        class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Start Meeting"><i
                                            class="fa fa-play"></i></a>
                                <a href="{{ route('admin.live-videos.edit',$data->id) }}"
                                        class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Edit"><i
                                         class="fa fa-edit"></i></a>
                            @endif
                            
                            <button type="button" class="btn btn-sm btn-secondary" data-toggle="tooltip"
                                title="Delete"
                                onclick="event.preventDefault(); if(confirm('Are you sure to delete this video?')){ document.getElementById('delete-live-video-{{ $data->id }}').submit();}">
                            <i class="fa fa-times"></i> 
                            </button>
                            <form id="delete-live-video-{{ $data->id }}"
                                    action="{{ route('admin.live-videos.destroy', $data->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                            </form>
                            <button type="button" value="{{$data->meeting_id}}" id="{{$data->id}}" class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Transfer to Recorded Videos" onclick="getRec(this)">
                                <i class="fa fa-external-link"></i>
                            </button>
                        </div>
                    </td>
                </tr>
                @endforeach
                @else
                <tr class="no-data">
                    <td colspan="7" class="text-center">No data found</td>
                </tr>
                @endif
            </tbody>
            <tfoot>
                <tr>
                <th colspan="7">
                    <div style="float:right;">{{ $videos->appends(['inactives' => $inactives->currentPage()])->links() }}</div>
                </th>
                </tr>
            </tfoot>
        </table>
        <hr>
        <h4 align="center">Finished Meetings</h4>
        <table id="live-videos-inactive" class="table table-bordered table-striped table-vcenter">
            <thead>
                <tr>
                    <th style="text-transform: none !important;">Sl.No</th>
                    <th style="text-transform: none !important;">Meeting Title</th>
                    <th style="text-transform: none !important;">Meeting Id</th>
                    <th style="text-transform: none !important;">Packages</th>
                    <th style="text-transform: none !important;">Scheduled Date / Time</th>
                    <th style="text-transform: none !important;">Category</th>
                    <th style="text-transform: none !important;">Actions</th>

                </tr>
            </thead>
            <tbody>
                @if($inactives->count())
                @foreach ($inactives as $data)
                <tr>
                    <td class="text-center"> {{ $loop->iteration }} </td>
                    <td class="font-w600"> {{ @$data->title }}</td>
                    <td class="font-w600"> {{ @$data->meeting_id }}</td>
                    <td class="d-none d-sm-table-cell">
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            @foreach ($data->packages as $package)
                                <span class="badge badge-success">{{ $package->name }}</span>
                            @endforeach
                        </div>
                    </td>
                    <td>
                        {{ Carbon::parse(@$data->schedule)->format('d M Y h:i:s A') }}
                    </td>
                    <td>
                        {{ @$data->category->category}}
                    </td>
                    <td>
                        <div class="btn-group">
                            @if($data->schedule >= Carbon::now())
                                <a target="_blank" href="{{$data->start_link}}"
                                        class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Start Meeting"><i
                                            class="fa fa-play"></i></a>
                                <a href="{{ route('admin.live-videos.edit',$data->id) }}"
                                        class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Edit"><i
                                         class="fa fa-edit"></i></a>
                            @endif
                            
                            <button type="button" class="btn btn-sm btn-secondary" data-toggle="tooltip"
                                title="Delete"
                                onclick="event.preventDefault(); if(confirm('Are you sure to delete this video?')){ document.getElementById('delete-live-video-{{ $data->id }}').submit();}">
                            <i class="fa fa-times"></i> 
                            </button>
                            <form id="delete-live-video-{{ $data->id }}"
                                    action="{{ route('admin.live-videos.destroy', $data->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                            </form>
                            <button type="button" value="{{$data->meeting_id}}" id="{{$data->id}}" class="btn btn-sm btn-secondary" data-toggle="tooltip" title="Transfer to Recorded Videos" onclick="getRec(this)">
                                <i class="fa fa-external-link"></i>
                            </button>
                        </div>
                    </td>
                </tr>
                @endforeach
                @else
                <tr class="no-data">
                    <td colspan="7" class="text-center">No data found</td>
                </tr>
                @endif
            </tbody>
            <tfoot>
                <tr>
                <th colspan="7">
                    <div style="float:right;">{{ $inactives->appends(['videos' => $videos->currentPage()])->links() }}</div>
                </th>
                </tr>
            </tfoot>
        </table>
        </div>
    </div>
    <!-- END Dynamic Table Full -->
</div>               
<!-- END Page Content -->

@endsection
@section('js_after')
<script>
    $(function() {
        $('#live-videos').DataTable({
            "dom": '<"pull-left"f><"pull-right"l>tip',
            "paging": false,
            language : {
                sLengthMenu: "Show _MENU_"
            },
            "bInfo" : false
        });
        
    });
    $(function() {
        $('#live-videos-inactive').DataTable({
            "dom": '<"pull-left"f><"pull-right"l>tip',
            "paging": false,
            language : {
                sLengthMenu: "Show _MENU_"
            },
            "bInfo" : false
        });
        
    });
</script>
<script>
    function getRec(button)
    {
        $.ajax({
          url: "{{ route('admin.recordings') }}",
          type:"get",
          data:{
                id:button.value,
                video:button.id,
            },
          success:function(response){
            console.log(response);
            
            if(response) {
                alert(response.success);
            }
          },
        });
    }
</script>
@endsection

resources/views/admin/live-videos/show.blade.php
@extends('admin.layout.app')

@section('content')
<!-- Page Content -->
<div class="content">
    <nav class="breadcrumb bg-white push">
    <a class="breadcrumb-item" href="{{ route('admin.home') }}">Dashboard</a>
        <a class="breadcrumb-item" href="{{ route('admin.recorded-videos.index') }}">Recorded Videos</a>
        <span class="breadcrumb-item active">Show</span>
    </nav>

    <div class="row py-30">
        <div class="col-md-12 col-xl-12">
            <table class="container table">
                <tr>
                    <td>
                        <video class="container" width="100%" height="100%" autoplay controls controlsList="nodownload">
                            <source src="{{$video->video_link}}" type="video/mp4">
                        </video>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h4 align="center">{{$video->title}}</h4>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p align="justify">{{$video->description}}</p>
                    </td>
                </tr>
                <tr>
                    <td align="center">
                        <h5>Asigned to : </h5>
                        @foreach ($video->package as $package)
                            <span class="badge badge-success">{{$package->getPackage->name}}</span>
                        @endforeach
                    </td>
                </tr>
                
            </table>
        </div>
    </div>
</div>               
<!-- END Page Content -->

@endsection
@section('js_after')
<script>
    document.addEventListener('contextmenu', event => event.preventDefault());
    document.onkeydown = function (e) {
        if (event.keyCode == 123) {
            return false;
        }
        if (e.ctrlKey && e.shiftKey && (e.keyCode == 'I'.charCodeAt(0) || e.keyCode == 'i'.charCodeAt(0))) {
            return false;
        }
        if (e.ctrlKey && e.shiftKey && (e.keyCode == 'C'.charCodeAt(0) || e.keyCode == 'c'.charCodeAt(0))) {
            return false;
        }
        if (e.ctrlKey && e.shiftKey && (e.keyCode == 'J'.charCodeAt(0) || e.keyCode == 'j'.charCodeAt(0))) {
            return false;
        }
        if (e.ctrlKey && (e.keyCode == 'U'.charCodeAt(0) || e.keyCode == 'u'.charCodeAt(0))) {
            return false;
        }
        if (e.ctrlKey && (e.keyCode == 'S'.charCodeAt(0) || e.keyCode == 's'.charCodeAt(0))) {
            return false;
        }
    }
</script>
@endsection